### ISSUE TITLE
Picture from image. entity

### ISSUE THREAD

**Issue by marsal-75** [energywave/multinotify#7]
Hi, as I already mentioned on the blog, I would like to be able to include a picture of an "image." entity type in the notification sent to mobile devices, in my case Android. I think this could be useful for people like me who own Ezviz cameras, but not only. Thank you for your work!

**Comment by energywave** [comment]
Sorry for late reply... Can you please tell me why should be that useful? Can't you use the camera. entity that will be automatically used to obtain a screenshot in the notications? (please, dont let me search between comments on the blog... :D )

**Comment by marsal-75** [comment]
Hi,
just because the snapshot taken from the motion notification using camera.entity does not accurately capture the event (for example, a moth passing in front of the camera) as it is captured a few seconds later, while the image.ultima_immagine_motion entity created by the Ezviz integration already contains the image of the event that triggered the alarm. In the "standard" notifications, I can send it like this:
```
action: notify.dispositivi_mobili
data:
  message: Camera garage ha rilevato un movimento.
  data:
    channel: sicurezza
    importance: high
    image: /api/image_proxy/image.camera_garage_ultima_immagine_motion
```
but with your package, this is not possible.
Thank you.

**Comment by energywave** [comment]
Thank you for pointing out!
I've implemented automatic image entities attachment with Android and iOS app, HTML5 push notifications and Pushover in the latest 3.8.4 release. Let me know if it works correctly for you!
You simply have to specify the image entity_id in the attachment parameter when you call multinotify (don't use the image_proxy manually as that works only for companion app. Multinotify use the most appropriate way of attaching the image for every platform).
Please see README.md file for further details at the attachment section.
Example to send the image to companion app, HTML5 and Pushover with one single action:

```
action: script.multinotify
data:
  title: Image entity test
  message: Send the image entity snapshot
  attachment: image.living_room_snapshot
  notify_pushover: notify.pushover
  notify_app: notify.your_smartphone_name
  notify_html5: notify.html5_your_browsername
```
