### ISSUE TITLE
Music not resuming anymore

### ISSUE THREAD

**Issue by PaulBiod** [energywave/multinotify#8]
Hi,
hope you're doing well.
Since the last versions (of  AMP or HA), the resume fuction doesn't work anymore.
I tried a simple script : 
1) play musique on an alexa device (radio)
2) wait 30 seconds
3) make a tts or an announcement

I tried on echo show 5/8/echo pop

Is it working on your side ?
Thanks

**Comment by kingunlim** [comment]
i also think something is broken atm?
my music will resume, but the volume level will not restore anymore...

maybe you can have a look?

best regards

**Comment by energywave** [comment]
> Is it working on your side ? Thanks

Hello, sorry for late reply. Alexa changed something and the command I used to resume the play stopped working. If you updated to the latest version I released that should be working again. I'm now using the command to issue a command as it was told by voice and it works on my side. I'll close the issue, if you have any difficulties after having updated just reply and we'll reopen the issue.



> i also think something is broken atm? my music will resume, but the volume level will not restore anymore...

That is 99,99999% an AMP problem. It uses a websocket to receive updates from Amazon servers and it can happen that the websocket is dropped. When that happens the volume on HA side is not anymore updated from the devices so that we don't know the REAL volume it was on the device so that my script will resume a WRONG volume (not corresponding to the one on the real device).
To reduce that risk I'm using these automations (the first one is a bonus to tell you if AMP requires a relogin, that's not the specific case, the second automation reduces the probability of websocket dropped as it reload the AMP every night):

```
  # Notify if Alexa Media Player requires a relogin
  - id: 11996eb7-ed6a-4592-af88-994534b3c836
    alias: Alexa - Notify - Relogin Alexa Media Player
    triggers:
      - trigger: event
        event_type: "alexa_media_relogin_required"
    actions:
      - action: script.multinotify
        data:
          title: Alexa relogin
          message: Alexa Media Player requires a relogin on Home Assistant. Notifies will not be played until you'll do relogin.
          group: warning
          notify_app: notify.all_android_devices
          critical: true

  # Reload Alexa Media Player integration every night
  - id: 7a85ce07-9175-4f67-a728-c87968b5a80c
    alias: Alexa - Fix - Reload integration
    triggers:
      - trigger: time_pattern
        hours: "5"
        minutes: "30"
    actions:
      - action: homeassistant.reload_config_entry
        data: {}
        target:
          entity_id: media_player.pian_terreno
```

Side note: if you have a different issue please don't comment another issue, open your own issue :)
